services:

  app:
    build: .
    image: laravel-app:latest
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "
        touch database/database.sqlite &&
        chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache /var/www/database &&
        chmod -R 775 /var/www/storage /var/www/bootstrap/cache /var/www/database &&
        composer install &&
        php artisan migrate --force &&
        php artisan config:clear &&
        php artisan cache:clear &&
        php-fpm
        "

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  node:
    image: node:20
    container_name: laravel-node
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
    command: sh -c "npm ci && npm run dev"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  queue:
    build: .
    container_name: laravel-queue
    volumes:
      - .:/var/www
    command: php artisan queue:work --tries=3 --timeout=90
    depends_on:
      - redis
